accessing
errorToExceptionMap: aDictionary
	ErrorToExceptionMap := aDictionary